name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Rodar os testes do Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome